[package]
name = "RUST"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.4"
crossbeam-channel = "0.5.4"
parking_lot = "0.12.0"
backoff = "0.4.0"
